### ISSUE TITLE
Error during local installation 

### ISSUE THREAD

**Issue by jadoonf** [listendev/lstn#158]
### Describe the bug

Executing the installation script using 
`curl -sSfL https://lstn.dev/get | sh -s -- -b /usr/local/bin`

returns

```
install: /usr/local/bin//lstn: Permission denied
```

Please include:

- v0.3.1
- macos/arm64

### Steps to reproduce the behavior

Execute the command for local installation on macOS. 

### Expected vs actual behavior

Should install the binary in /usr/local/bin/lstn instead of 
install: /usr/local/bin//lstn

Looks like an extra `'/'` is being appended before `lstn`

### Logs

```
listendev/lstn info checking GitHub for latest tag
listendev/lstn info found version: 0.3.1 for v0.3.1/macos/arm64
install: /usr/local/bin//lstn: Permission denied
```

**Comment by leodido** [comment]
You need root privileges (sudo).

**Comment by leodido** [comment]
@jadoonf you need to give root privileges to the process installing it, not the one downloading it. :)

**Comment by leodido** [comment]
```bash
curl -sSfL https://lstn.dev/get -o install.sh
chmod +x install.sh
sudo ./install.sh -b /usr/local/bin
```

**Comment by jadoonf** [comment]
Works! Updated the docs accordingly.

**Comment by jadoonf** [comment]
@leodido do we intend on converting this into a one liner? and cleaning up the install.sh script post install?

**Comment by leodido** [comment]
If you look at other projects you'll notice they also use the one-liner we currently have in the README.

This is because we assume the user has privileges for the destination directory. Also installation with privileges (eg., `curl | sudo sh`) is universally considered bad practice nowadays. Thus, I'd avoid having it (or something similar) in the README.

But feel free to change it if you feel so. Closing this for now.
